export const CREATE_REVIEW = 'CREATE_REVIEW';
export const CREATE_REVIEW_ERROR = 'CREATE_REVIEW_ERROR';
export const UPDATE_REVIEW = 'UPDATE_REVIEW';
export const UPDATE_REVIEW_ERROR = 'UPDATE_REVIEW_ERROR';
export const DELETE_REVIEW = 'DELETE_REVIEW';
export const SELECT_REVIEW = 'SELECT_REVIEW';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const SIGNOUT_SUCCESS = 'SIGNOUT_SUCCESS';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';