export const CREATE_REVIEW = 'CREATE_REVIEW';
export const CREATE_REVIEW_ERROR = 'CREATE_REVIEW_ERROR';
export const UPDATE_REVIEW = 'UPDATE_REVIEW';
export const UPDATE_REVIEW_ERROR = 'UPDATE_REVIEW_ERROR';